version: '3.5'

services:
  img-upload-app:
    container_name: img-upload-app
    image: kastentx/max-cropping-tool
    ports:
      - '3000:3000'

  max-model:
    container_name: cors-max-imgseg
    image: kastentx/cors-max-imgseg
    ports:
      - '5000:5000'
    environment:
      - CORS_ENABLE=true
