version: '3.5'

services:
  img-upload-app:
    container_name: img-upload-app
    image: kastentx/img-upload-app
    ports:
      - '4444:4444'

  max-model:
    container_name: cors-max-imgseg
    image: kastentx/cors-max-imgseg
    ports:
      - '5000:5000'
    environment:
      - CORS_ENABLE=true
