version: '3.5'

services:
  img-upload-app:
    container_name: img-upload-app
    image: kastentx/img-upload-app
    ports:
      - '4444:4444'
    environment:
      - REACT_APP_CLOUDANT_USER=''
      - REACT_APP_CLOUDANT_PW=''

  max-model:
    container_name: cors-dualmode-imgseg
    image: kastentx/cors-dualmode-imgseg
    ports:
      - '5000:5000'
    environment:
      - CORS_ENABLE=true
