version: '3.5'

services:
  max-cropping-tool:
    container_name: max-cropping-tool
    image: kastentx/max-cropping-tool
    ports:
      - '3000:3000'

  max-model:
    container_name: max-image-segmenter
    image: codait/max-image-segmenter
    ports:
      - '5000:5000'
    environment:
      - CORS_ENABLE=true
