apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: img-upload-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: img-upload-app
  template:
    metadata:
      labels:
        app: img-upload-app
    spec:
      containers:
      - name: img-upload-app
        image: kastentx/img-upload-app
        env:
        - name: REACT_APP_DEPLOY_TYPE
          value: 'KUBE'
        - name: REACT_APP_CLOUDANT_USER
          value: "----------------"
        - name: REACT_APP_CLOUDANT_PW
          value: "----------------"
        - name: REACT_APP_KUBE_IP
          value: "---.---.---.---"
        ports:
        - containerPort: 4444
          hostPort: 4444
      - name: max-mobile-imgseg
        image: kastentx/cors-dualmode-imgseg
        env:
        - name: CORS_ENABLE
          value: 'true'
        ports:
        - containerPort: 5000
          hostPort: 5000